### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by ImNotAVirus** [ImNotAVirus/elvengard_network#7]
The project currently has few documentation and is therefore very difficult to use.

It would be nice to have documentation available online at [hexdocs](https://hexdocs.pm/) as well as documentation of all modules, functions and callbacks of the project.

**Comment by ImNotAVirus** [comment]
This issue is not yet fixed, many guides are still missing

**Comment by thelastinuit** [comment]
@ImNotAVirus is this still in development? as in, the project is alive but slow development.

**Comment by ImNotAVirus** [comment]
Development is currently on hold as I am focusing on a private version of [https://github.com/ImNotAVirus/Flugel-NostaleEmu](https://github.com/ImNotAVirus/Flugel-NostaleEmu).
